language: bash

services:
  - docker

env:
  matrix:
    - WORDPRESS_VER=4 PHP_VER=7.2
    - WORDPRESS_VER=4 PHP_VER=7.1
    - WORDPRESS_VER=4 PHP_VER=7.0
    - WORDPRESS_VER=4 PHP_VER=5.6 GITHUB_RELEASE=1

script:
  - set -e
  - make test
  - cp docker.mk Makefile
  - tar -czf wordpress4docker.tar.gz docker-compose.yml docker-sync.yml Makefile .env traefik.yml

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - wordpress4docker.tar.gz
  on:
    tags: true
    condition: $GITHUB_RELEASE = 1
